apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auto-inquiry-form-prod

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

patchesStrategicMerge:
  - backend-patch.yaml
  - frontend-patch.yaml
  - ingress-patch.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=WARNING

secretGenerator:
  - name: app-secrets
    behavior: replace
    files:
      - secrets.env

images:
  - name: auto-inquiry-form/backend
    newTag: v1.0.0
  - name: auto-inquiry-form/frontend
    newTag: v1.0.0