apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: auto-inquiry-form
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done']
      - name: run-migrations
        image: auto-inquiry-form/backend:latest
        command: ['alembic', 'upgrade', 'head']
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
      containers:
      - name: backend
        image: auto-inquiry-form/backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: screenshots
          mountPath: /app/screenshots
        resources:
          limits:
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 40
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 5
      volumes:
      - name: screenshots
        persistentVolumeClaim:
          claimName: screenshots-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: auto-inquiry-form
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: screenshots-pvc
  namespace: auto-inquiry-form
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi